export const apiKey = "fb4f157d597a441898e155850241504";

export const weatherImage = {
    "Sunny": require("../assets/day/Sunny.png"),
    "Partly Cloudy ": require("../assets/day/Partly-cloudy.png"),
    "Partly Cloudy": require("../assets/day/Partly-cloudy.png"),
    "Partly cloudy ": require("../assets/day/Partly-cloudy.png"),
    "Partly cloudy": require("../assets/day/Partly-cloudy.png"),
    "Cloudy ": require("../assets/day/Cloudy.png"),
    "Overcast ": require("../assets/day/Overcast.png"),
    "Overcast": require("../assets/day/Overcast.png"),
    "Mist": require("../assets/day/Mist.png"),
    "Patchy rain nearby": require("../assets/day/Patchy-rain-possible.png"),
    "Patchy snow nearby": require("../assets/day/Patchy-snow-possible.png"),
    "Pathcy sleet nearby": require("../assets/day/Patchy-sleet-possible.png"),
    "Patchy freezing drizzle possible": require("../assets/day/Patchy-freezing-drizzle-possible.png"),
    "Thundery outbreaks in nearby": require("../assets/day/Thundery-outbreaks-possible.png"),
    "Blowing snow": require("../assets/day/Blowing-snow.png"),
    "Blizzard": require("../assets/day/Blizzard.png"),
    "Fog": require("../assets/day/Fog.png"),
    "Freezing fog": require("../assets/day/Freezing-fog.png"),
    "Patchy light drizzle": require("../assets/day/Patchy-light-drizzle.png"),
    "Light drizzle": require("../assets/day/Light-drizzle.png"),
    "Freezing drizzle": require("../assets/day/Freezing-drizzle.png"),
    "Heavy freezing drizzle": require("../assets/day/Heavy-freezing-drizzle.png"),
    "Patchy light rain": require("../assets/day/Patchy-light-rain.png"),
    "Light rain": require("../assets/day/Light-rain.png"),
    "Moderate rain at times": require("../assets/day/Moderate-rain-at-times.png"),
    "Moderate rain": require("../assets/day/Moderate-rain.png"),
    "Heavy rain at times": require("../assets/day/Heavy-rain-at-times.png"),
    "Heavy rain": require("../assets/day/Heavy-rain.png"),
    "Light freezing rain": require("../assets/day/Light-freezing-rain.png"),
    "Moderate or heavy freezing rain": require("../assets/day/Moderate-or-heavy-freezing-rain.png"),
    "Light sleet": require("../assets/day/Light-sleet.png"),
    "Moderate or heavy sleet": require("../assets/day/Moderate-or-heavy-sleet.png"),
    "Patchy light snow": require("../assets/day/Patchy-light-snow.png"),
    "Light snow": require("../assets/day/Light-snow.png"),
    "Patchy moderate snow": require("../assets/day/Patchy-moderate-snow.png"),
    "Patchy heavy snow": require("../assets/day/Patchy-heavy-snow.png"),
    "Heavy snow": require("../assets/day/Heavy-snow.png"),
    "Ice pellets": require("../assets/day/Ice-pellets.png"),
    "Light rain shower": require("../assets/day/Light-rain-shower.png"),
    "Moderate or heavy rain shower": require("../assets/day/Moderate-or-heavy-rain-shower.png"),
    "Torrential rain shower": require("../assets/day/Torrential-rain-shower.png"),
    "Light sleet showers": require('../assets/day/Light-sleet-showers.png'),
    "Moderate or heavy sleet showers": require("../assets/day/Moderate-or-heavy-sleet-showers.png"),
    "Light snow showers": require("../assets/day/Light-snow-showers.png"),
    "Moderate or heavy snow showers": require("../assets/day/Moderate-or-heavy-snow-showers.png"),
    "Light showers of ice pellets": require("../assets/day/Light-showers-of-ice-pellets.png"),
    "Moderate or heavy showers of ice pellets": require("../assets/day/Moderate-or-heavy-showers-of-ice-pellets.png"),
    "Patchy light rain with thunder": require("../assets/day/Patchy-light-rain-with-thunder.png"),
    "Moderate or heavy rain with thunder": require("../assets/day/Moderate-or-heavy-rain-with-thunder.png"),
    "Patchy light snow with thunder": require("../assets/day/Patchy-light-snow-with-thunder.png"),
    "Moderate or heavy snow with thunder": require("../assets/day/Moderate-or-heavy-snow-with-thunder.png")
}

export const weatherImageNight = {
    "Clear ": require("../assets/night/Clear.png"),
    "Clear": require("../assets/night/Clear.png"),
    "Partly Cloudy ": require("../assets/night/Partly-cloudy.png"),
    "Partly Cloudy": require("../assets/night/Partly-cloudy.png"),
    "Partly cloudy": require("../assets/night/Partly-cloudy.png"),
    "Partly cloudy ": require("../assets/night/Partly-cloudy.png"),
    "Cloudy ": require("../assets/night/Cloudy.png"),
    "Overcast ": require("../assets/night/Overcast.png"),
    "Overcast": require("../assets/night/Overcast.png"),
    "Mist": require("../assets/night/Mist.png"),
    "Patchy rain nearby": require("../assets/night/Patchy-rain-possible.png"),
    "Patchy snow nearby": require("../assets/night/Patchy-snow-possible.png"),
    "Pathcy sleet nearby": require("../assets/night/Patchy-sleet-possible.png"),
    "Patchy freezing drizzle possible": require("../assets/night/Patchy-freezing-drizzle-possible.png"),
    "Thundery outbreaks in nearby": require("../assets/night/Thundery-outbreaks-possible.png"),
    "Blowing snow": require("../assets/night/Blowing-snow.png"),
    "Blizzard": require("../assets/night/Blizzard.png"),
    "Fog": require("../assets/night/Fog.png"),
    "Freezing fog": require("../assets/night/Freezing-fog.png"),
    "Patchy light drizzle": require("../assets/night/Patchy-light-drizzle.png"),
    "Light drizzle": require("../assets/night/Light-drizzle.png"),
    "Freezing drizzle": require("../assets/night/Freezing-drizzle.png"),
    "Heavy freezing drizzle": require("../assets/night/Heavy-freezing-drizzle.png"),
    "Patchy light rain": require("../assets/night/Patchy-light-rain.png"),
    "Light rain": require("../assets/night/Light-rain.png"),
    "Moderate rain at times": require("../assets/night/Moderate-rain-at-times.png"),
    "Moderate rain": require("../assets/night/Moderate-rain.png"),
    "Heavy rain at times": require("../assets/night/Heavy-rain-at-times.png"),
    "Heavy rain": require("../assets/night/Heavy-rain.png"),
    "Light freezing rain": require("../assets/night/Light-freezing-rain.png"),
    "Moderate or heavy freezing rain": require("../assets/night/Moderate-or-heavy-freezing-rain.png"),
    "Light sleet": require("../assets/night/Light-sleet.png"),
    "Moderate or heavy sleet": require("../assets/night/Moderate-or-heavy-sleet.png"),
    "Patchy light snow": require("../assets/night/Patchy-light-snow.png"),
    "Light snow": require("../assets/night/Light-snow.png"),
    "Patchy moderate snow": require("../assets/night/Patchy-moderate-snow.png"),
    "Patchy heavy snow": require("../assets/night/Patchy-heavy-snow.png"),
    "Heavy snow": require("../assets/night/Heavy-snow.png"),
    "Ice pellets": require("../assets/night/Ice-pellets.png"),
    "Light rain shower": require("../assets/night/Light-rain-shower.png"),
    "Moderate or heavy rain shower": require("../assets/night/Moderate-or-heavy-rain-shower.png"),
    "Torrential rain shower": require("../assets/night/Torrential-rain-shower.png"),
    "Light sleet showers": require('../assets/night/Light-sleet-showers.png'),
    "Moderate or heavy sleet showers": require("../assets/night/Moderate-or-heavy-sleet-showers.png"),
    "Light snow showers": require("../assets/night/Light-snow-showers.png"),
    "Moderate or heavy snow showers": require("../assets/night/Moderate-or-heavy-snow-showers.png"),
    "Light showers of ice pellets": require("../assets/night/Light-showers-of-ice-pellets.png"),
    "Moderate or heavy showers of ice pellets": require("../assets/night/Moderate-or-heavy-showers-of-ice-pellets.png"),
    "Patchy light rain with thunder": require("../assets/night/Patchy-light-rain-with-thunder.png"),
    "Moderate or heavy rain with thunder": require("../assets/night/Moderate-or-heavy-rain-with-thunder.png"),
    "Patchy light snow with thunder": require("../assets/night/Patchy-light-snow-with-thunder.png"),
    "Moderate or heavy snow with thunder": require("../assets/night/Moderate-or-heavy-snow-with-thunder.png")
}